export function mapCat(cat: any) {
  return {
    id: cat.id,
    image: cat.image?.url || null,
    name: cat.name,
    description: cat.description,
    weight: cat.weight.metric,
    life_span: cat.life_span,
    sheeding: cat.shedding_level,
    child_friendly: cat.child_friendly,
    stranger_friendly: cat.stranger_friendly,
    dog_friendly: cat.dog_friendly,
    playfulness: cat.energy_level,
    intelligence: cat.intelligence,
    temperament: cat.temperament,
    social_needs: cat.social_needs,
    activity_level: cat.energy_level,
    shedding_level: cat.shedding_level,
    indoors: cat.indoor,
    grooming: cat.grooming,
    health_issues: cat.health_issues,
    vocalisation: cat.vocalisation,
    hairless: cat.hairless,
    rare: cat.rare,
    wikipedia_url: cat.wikipedia_url || null,
    hypoallergenic: cat.hypoallergenic,
    short_legs: cat.short_legs,
    suppresed_tail: cat.suppressed_tail,
    affectionate: cat.affection_level,
  };
}
